name: Rebase Check

on:
  pull_request:
    types: [assigned, unassigned, labeled, unlabeled, opened, edited, reopened, synchronize]
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check rebased
        run: |
          git checkout ${{ github.head_ref }}
          git checkout ${{ github.base_ref }}
          base_hash=$(git show-ref --heads -s ${{github.base_ref}} ) && pr_merge_hash=$(git merge-base ${{github.base_ref}} ${{github.head_ref}}) && ([ "${base_hash}" = "${pr_merge_hash}" ] && echo "Already rebased, merge-base commit  ${base_hash}" || exit 1)
